### ISSUE TITLE
NoSuchMethodException with the MTS Script.

### ISSUE THREAD

**Issue by heyhey546** [kiooeht/ModTheSpire#101]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
Yes

**Crash Log**
```
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.charSelect.CharacterOption.CtorSwitch:
No method [<ctor>(java.lang.String, com.megacrit.cardcrawl.characters.AbstractPlayer, java.lang.String, java.lang.String)] found on
class [com.megacrit.cardcrawl.screens.charSelect.CharacterOption]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:271)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional context**
I'm running it from the script, which from what I understand makes it run with Java 8 whether or not I initially have it installed. But for some reason, I still get NoSuchMethodException. Help?

**Comment by kiooeht** [comment]
Based on your last issue (https://github.com/kiooeht/ModTheSpire/issues/100), you're running Slay the Spire version 10-04-2018. You need to update to the latest version 10-11-2018. BaseMod only supports the newest version of Slay the Spire.

**Comment by skrrtpow** [comment]
> Based on your last issue (#100), you're running Slay the Spire version 10-04-2018. You need to update to the latest version 10-11-2018. BaseMod only supports the newest version of Slay the Spire.

I'm also having the same problem, but I have updated to the latest version but it is still not working:

java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.DeathScreen.ForceUnlock:
No method named [calculateUnlockProgress] found on
class [com.megacrit.cardcrawl.screens.DeathScreen]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)
