### ISSUE TITLE
Unable to open the game

### ISSUE THREAD

**Issue by calvinteng1** [kiooeht/ModTheSpire#104]
**Crash Log**
```
Paste the ENTIRE log here. Including the very top of the log and the full error.
```

com.megacrit.cardcrawl.helpers.Prefs[] __pref = new com.megacrit.cardcrawl.helpers.Prefs[]{pref};
ThMod_FnH.patches.AscensionPatch$CharSelectFix.Insert($0, $$, c, __pref);
pref = __pref[0];
}
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: javassist.CannotCompileException: [source error] Insert(com.megacrit.cardcrawl.screens.charSelect.CharacterOption,com.megacrit.cardcrawl.characters.AbstractPlayer,com.megacrit.cardcrawl.helpers.Prefs[]) not found in ThMod_FnH.patches.AscensionPatch$CharSelectFix
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:209)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:144)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)
Caused by: javassist.CannotCompileException: [source error] Insert(com.megacrit.cardcrawl.screens.charSelect.CharacterOption,com.megacrit.cardcrawl.characters.AbstractPlayer,com.megacrit.cardcrawl.helpers.Prefs[]) not found in ThMod_FnH.patches.AscensionPatch$CharSelectFix
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:183)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:207)
	... 4 more
Caused by: compile error: Insert(com.megacrit.cardcrawl.screens.charSelect.CharacterOption,com.megacrit.cardcrawl.characters.AbstractPlayer,com.megacrit.cardcrawl.helpers.Prefs[]) not found in ThMod_FnH.patches.AscensionPatch$CharSelectFix
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:749)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Additional context**
Not sure what the problem is. I have update both ModTheSpire and Basemod (the latest).

**Comment by kiooeht** [comment]
I think you're using an outdated version of the Marisa mod.
Grab the latest from here https://github.com/lf201014/STS_ThMod_MRS/releases

**Comment by calvinteng1** [comment]
wow. It works now. Thanks a lot kiooeht. Saving the day!
