### ISSUE TITLE
Can't use mod the spire

### ISSUE THREAD

**Issue by Rafaumm** [kiooeht/ModTheSpire#108]
it show this and don't open don't know how to resolve help

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (10-18-2018)
 - ModTheSpire (3.3.0)
Mod list:
 - basemod (4.0.2)
 - ReplayTheSpireMod (1.1.15)
 - sts-mod-the-blackbeard (0.1.4)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetColorSpecificCardSwitch:
No method [getColorSpecificCard(com.megacrit.cardcrawl.characters.AbstractPlayer$PlayerClass, com.megacrit.cardcrawl.random.Random)] found on
class [com.megacrit.cardcrawl.helpers.CardLibrary]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:271)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
Today's Slay the Spire update broke BaseMod. I've just updated it (https://github.com/daviscook477/BaseMod/releases/tag/v5.0.0), but you may have to wait for other mods to update for them to work. Character mods in particular are broken and need to be updated.
