### ISSUE TITLE
Something's wrong

### ISSUE THREAD

**Issue by ZZTKKF** [kiooeht/ModTheSpire#128]
What can it mean, can someone help me with this? It can not run, it only showes me this:

![screenshot_1](https://user-images.githubusercontent.com/46088381/50387633-8937ad80-0701-11e9-88a9-8ec105e7b675.png)

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (08-02-2018)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.4.0)
 - constructmod (0.9.992)
 - fruitymod-sts (1.0.3)
 - sts-mod-the-blackbeard (1.6.0)
java.lang.NullPointerException: in is null
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:76)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.<init>(MTSClassLoader.java:33)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:182)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
Your actual error is most likely caused by having a corrupt mod download. One or more of the mods you're using (BaseMod, Construct, FruityMod, Blackbeard) are corrupt. You'll have to re-download the offending one to get it working.

However, you also have another error:
> Slay the Spire (08-02-2018)

You're running an extremely old version of the game. The latest is 12-20-2018. You need to update to latest version for mods to work.
