### ISSUE TITLE
Game not working?

### ISSUE THREAD

**Issue by just000jay** [kiooeht/ModTheSpire#131]
Recently I wanted to install mods on my slay the spire game, and they worked. But now I want to play without mods and my game wont start. I re-installed the game and it still launches mod the spire, wich i don't want it to do. when I'm trying to start the game with mod the spire it gives me this error ( idk if it is an error but it get's stuck here)
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (01-03-2019)
 - ModTheSpire (3.6.3)
Mod list:

Starting game...
Exception in thread "Thread-4" java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: Provider org.apache.logging.log4j.core.impl.Log4jProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.logging.log4j.util.ProviderUtil.loadProviders(ProviderUtil.java:101)
	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:142)
	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:126)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:89)
	at com.megacrit.cardcrawl.desktop.DesktopLauncher.<clinit>(DesktopLauncher.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:261)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

If you can help me, thank you :)

**Comment by kiooeht** [comment]
That's an odd one. Did you do the optional part of the MTS install where you replace Slay the Spire with MTS? If you did, that's probably why.

You should switch over to using the [Steam Workshop](https://steamcommunity.com/workshop/browse/?appid=646570). Now that Workshop support is official, all future updates are available there instead of GitHub.

I don't think it will do anything, but let me know if switching fixes it or not.

**Comment by NhatMinh0208** [comment]
Same problem with me here. 
~~~~
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (01-03-2019)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.5.0)
 - stslib (1.10.0)
 - beakedthecultist-sts (0.6.1)
 - BlackRuseMod (0.9.3)
 - ClockworkMod (0.0.3)
 - constructmod (1.0.3)
 - Friendly_Minions_0987678 (0.1.1)
 - fruitymod-sts (1.0.3)
 - gatherermod (0.5.0)
 - jester (1.1.1)
 - MadScienceMod (0.3.0)
 - sagemod (0.4.1)
 - Slimebound (1.0.0)
 - SneckoMod (0.0.3)
 - sts-mod-the-blackbeard (1.6.3)
 - chronomuncher (0.10.7)
 - Sts-JuggernautMod (0.1.2)
 - Sts-MarksmanMod (0.3.3)
 - MysticMod (0.15.0)
 - Sts-Necromancer (0.1.2)
 - Sts-ValiantMod (1.2.3)
 - TheWarrior (0.1.3)
 - TS05_Marisa (0.14.8)
 - witchmod (1.1.3)
 - AscensionMinus (0.2.1)
 - ascensionmod (1.0.0)
 - aspiration (0.7.0)
 - betterrewardsmod (4.0.8)
 - BlakkMod (2.3)
 - cagethespire (2.0.0)
 - coloredmap (2.2.0)
 - conspire (1.5.4)
 - customactiv (1.0.0)
 - Custom Cards (1.1.0)
 - defaultmod (1.0)
 - fetchmod (1.1.0)
 - HighlightPath (0.0.2)
 - hubris (0.18.0)
 - infinitespire (0.9.2)
 - lotusmark (0.1)
 - mimicmod (0.1.3)
 - StSMod_Clawfect (0.1.0)
 - StSMod_GremlinsDice (0.1.0)
 - relicrelevancereorder (3.2.1.2)
 - relicsorter (1.1.2)
 - ReplayTheSpireMod (1.3.14)
 - RNG (1)
 - ShopMod (1.0.3)
 - SpikesRelics (0.022)
 - StrawberrySpire (0.4.3)
 - StSExporter (0.4.2)
 - STS_AlwaysWhale (0.1.0)
 - jedi (0.2.4)
 - superfastmode (1.0.2)

Begin patching...
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...
Patch Class: [ascensionminus.patches.BattleRewardPatch$RicherBosses]
 - Patching [com.megacrit.cardcrawl.rooms.AbstractRoom.update()]
 - Adding Insert @ r115 (abs:318)...

com.evacipated.cardcrawl.modthespire.patcher.PatchingException: javassist.CannotCompileException: [source error] no such field: tmp
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:209)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:150)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:207)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javassist.CannotCompileException: [source error] no such field: tmp
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:183)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:207)
	... 4 more
Caused by: compile error: no such field: tmp
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.TypeChecker.atArrayInit(TypeChecker.java:186)
	at javassist.compiler.ast.ArrayInit.accept(ArrayInit.java:29)
	at javassist.compiler.TypeChecker.atNewArrayExpr(TypeChecker.java:162)
	at javassist.compiler.TypeChecker.atNewExpr(TypeChecker.java:144)
	at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:743)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more
~~~~
Maybe compatibility issue between ModTheSpire v3.6.3 and Slay the Spire patch 54? Considering it added Steam Workshop support.

**Comment by kiooeht** [comment]
1. That is not the same problem at all.
2. Your problem is that you're using Ascension Minus, which appears not to of been updated for patch 54.
3. As I said in my previous comment, you should switch to using the [Steam Workshop](https://steamcommunity.com/workshop/browse/?appid=646570). Now that Workshop support is official, **all future updates are available there instead of GitHub**. There are updates to most of the mods on your list there that aren't available outside of the Workshop.

**Comment by ItsonlyTelch** [comment]
I mean, You could post it here as well... For the people... use to coming here?
