### ISSUE TITLE
Crash when i start the game

### ISSUE THREAD

**Issue by NicoTine34** [kiooeht/ModTheSpire#140]
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (null)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.5.0)
 - betterrewardsmod (4.0.9)
 - coloredmap (2.3.0)
 - GooglyMod (1.6.1)
 - ShopMod (1.0.3)
 - STS_AlwaysWhale (0.1.0)

Begin patching...
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.

Setting isModded = true...2019-01-25 17:01:13,409 Thread-4 ERROR RollingFileManager (sendToDevs/logs/SlayTheSpire.log) java.io.FileNotFoundException: sendToDevs\logs\SlayTheSpire.log (Accès refusé) java.io.FileNotFoundException: sendToDevs\logs\SlayTheSpire.log (Accès refusé)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:640)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:608)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:115)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at com.megacrit.cardcrawl.core.Settings.<clinit>(Settings.java:17)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

2019-01-25 17:01:13,456 Thread-4 ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@57ef6bc2] unable to create manager for [sendToDevs/logs/SlayTheSpire.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@2c7394d2[pattern=sendToDevs/logs/SlayTheSpire_%d{yyyyMMddHHmm}{UTC}_%i.log.zip, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=2097152)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%d{HH:mm:ss.SSS}{UTC} %p %c{2}> %m%n, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@57ef6bc2] unable to create manager for [sendToDevs/logs/SlayTheSpire.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@2c7394d2[pattern=sendToDevs/logs/SlayTheSpire_%d{yyyyMMddHHmm}{UTC}_%i.log.zip, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[OnStartupTriggeringPolicy, SizeBasedTriggeringPolicy(size=2097152)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=%d{HH:mm:ss.SSS}{UTC} %p %c{2}> %m%n, filePermissions=null, fileOwner=null]]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:115)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at com.megacrit.cardcrawl.core.Settings.<clinit>(Settings.java:17)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

2019-01-25 17:01:13,466 Thread-4 ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:229)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
	at com.megacrit.cardcrawl.core.Settings.<clinit>(Settings.java:17)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)

2019-01-25 17:01:13,469 Thread-4 ERROR Null object returned for RollingFile in appenders.
2019-01-25 17:01:13,472 Thread-4 ERROR Unable to locate appender "RollingFile" for logger config "root"
Done.

Adding ModTheSpire to version...Done.

Initializing mods...
 - BaseMod
   - basemod.BaseMod
libgdx version 1.9.5
16:01:13.753 INFO basemod.BaseMod> initializeGson
16:01:13.765 INFO basemod.BaseMod> initializeTypeMaps
16:01:13.766 INFO basemod.BaseMod> Registered MonsterStrings
16:01:13.766 INFO basemod.BaseMod> Registered PowerStrings
16:01:13.767 INFO basemod.BaseMod> Registered CardStrings
16:01:13.767 INFO basemod.BaseMod> Registered RelicStrings
16:01:13.767 INFO basemod.BaseMod> Registered EventStrings
16:01:13.767 INFO basemod.BaseMod> Registered PotionStrings
16:01:13.767 INFO basemod.BaseMod> Registered CreditStrings
16:01:13.767 INFO basemod.BaseMod> Registered TutorialStrings
16:01:13.769 INFO basemod.BaseMod> Registered KeywordStrings
16:01:13.770 INFO basemod.BaseMod> Registered ScoreBonusStrings
16:01:13.770 INFO basemod.BaseMod> Registered CharacterStrings
16:01:13.770 INFO basemod.BaseMod> Registered UIStrings
16:01:13.771 INFO basemod.BaseMod> Registered OrbStrings
16:01:13.771 INFO basemod.BaseMod> Registered RunModStrings
16:01:13.772 INFO basemod.BaseMod> Registered BlightStrings
16:01:13.772 INFO basemod.BaseMod> Registered AchievementStrings
16:01:13.772 INFO basemod.BaseMod> initializePowerMap
16:01:14.307 INFO basemod.BaseMod> initializeUnderscorePowerIDs
   - 641ms
 - BetterRewards
   - skrelpoid.betterrewards.BetterRewardsMod
   - 4ms
 - Colored Map
   - coloredmap.ColoredMap
   - 3ms
 - Shop Mod
   - shopmod.ShopMod
   - 1ms
 - Always Whale
   - STS_AlwaysWhale.STS_AlwaysWhale
   - 0ms
Done.

Starting game...
16:01:14.403 INFO desktop.DesktopLauncher> time: 1548432074403
16:01:14.404 INFO desktop.DesktopLauncher> version: 2019-01-23
16:01:14.404 INFO desktop.DesktopLauncher> libgdx:  1.9.5
16:01:14.404 INFO desktop.DesktopLauncher> default_locale: fr_FR
16:01:14.404 INFO desktop.DesktopLauncher> default_charset: windows-1252
16:01:14.405 INFO desktop.DesktopLauncher> default_encoding: Cp1252
16:01:14.405 INFO desktop.DesktopLauncher> java_version: 1.8.0_144
16:01:14.405 INFO desktop.DesktopLauncher> os_arch: amd64
16:01:14.405 INFO desktop.DesktopLauncher> os_name: Windows 10
16:01:14.406 INFO desktop.DesktopLauncher> os_version: 10.0
16:01:14.407 INFO core.SystemStats> MEMORY STATS:
Free Memory: 118Mb
Max Memory: 228Mb
Allocated Memory: 228Mb
Unallocated Memory: 0Mb
Total Free Memory: 118Mb
Used Memory: 109Mb

16:01:14.408 INFO core.SystemStats> DISK STATS:
Total Space: 953 316Mb
Usable Space: 342 261Mb
Free Space: 342 261Mb

[Thread-4] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames
[Thread-4] WARN io.sentry.DefaultSentryClientFactory - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames16:01:14.503 INFO core.DisplayConfig> Reading info.displayconfig
16:01:14.508 INFO core.DisplayConfig> DisplayConfig successfully read.
16:01:14.530 INFO desktop.DesktopLauncher> Settings successfully loaded
16:01:14.530 INFO desktop.DesktopLauncher> Launching application...
16:01:15.809 INFO ststwitch.TwitchConfig> The 'twitchconfig.txt' already exists, not overwriting it.
16:01:15.899 INFO steam.SteamIntegration> [FAILURE] Steam API failed to initialize correctly.
16:01:15.926 INFO core.CardCrawlGame> No migration
16:01:15.929 INFO core.Settings> Initializing display settings...
16:01:15.929 INFO core.DisplayConfig> Reading info.displayconfig
16:01:15.930 INFO core.DisplayConfig> DisplayConfig successfully read.
16:01:15.930 INFO core.Settings> Initializing sound settings...
16:01:15.938 INFO core.Settings> Initializing game settings...
16:01:15.989 INFO localization.LocalizedStrings> Loc Strings load time: 28ms
16:01:15.990 INFO basemod.BaseMod> begin editing localization strings
16:01:15.991 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RunModStrings
16:01:15.995 INFO basemod.BaseMod> loadJsonStrings: com.megacrit.cardcrawl.localization.RelicStrings
16:01:16.039 INFO audio.MusicMaster> Music Volume: 0.14795771
16:01:16.042 INFO audio.SoundMaster> Sound Effect Volume: 0.13936077
16:01:16.042 INFO audio.SoundMaster> Loaded 360 Sound Effects
16:01:16.043 INFO audio.SoundMaster> SFX load time: 3ms
16:01:16.916 INFO cards.AbstractCard> Card Image load time: 867ms
16:01:16.917 INFO basemod.BaseMod> editting keywords
16:01:17.757 INFO helpers.ImageMaster> Texture load time: 837ms
16:01:18.006 INFO helpers.FontHelper> Font load time (Map Fonts): 203ms
16:01:18.115 INFO helpers.FontHelper> Font load time (Kreon Standard): 108ms
16:01:18.423 INFO helpers.FontHelper> Font load time (The rest of it): 308ms
16:01:18.526 INFO unlock.UnlockTracker> RED UNLOCKS:   9/9
16:01:18.526 INFO unlock.UnlockTracker> GREEN UNLOCKS: 9/9
16:01:18.526 INFO unlock.UnlockTracker> BLUE UNLOCKS: 9/9
16:01:18.526 INFO unlock.UnlockTracker> RELIC UNLOCKS: 12/18
16:01:18.572 INFO unlock.UnlockTracker> CARDS SEEN:    436/0
16:01:18.595 INFO unlock.UnlockTracker> RELICS SEEN:   147/0
16:01:18.596 INFO basemod.BaseMod> publish post refresh - refreshing unlocks
16:01:18.596 INFO basemod.BaseMod> begin editing cards
16:01:18.840 INFO panels.TopPanel> Twitch Integration enabled due to presence of 'twitch.properties` file.
16:01:18.858 INFO panels.TopPanel> Not starting twitch integration because enabled=false
16:01:19.014 INFO helpers.CardLibrary> Card load time: 417ms with 283 cards
16:01:19.016 INFO basemod.BaseMod> begin editing relics
16:01:19.160 INFO helpers.RelicLibrary> Relic load time: 136ms
16:01:19.162 INFO input.InputHelper> Setting input processor to Scroller
16:01:19.227 INFO basemod.BaseMod> postCreateStartingRelics for: IRONCLAD
16:01:19.227 INFO basemod.BaseMod> postCreateStartingRelics adding [ Burning Blood ]
16:01:19.914 INFO basemod.BaseMod> postCreateStartingRelics for: THE_SILENT
16:01:19.915 INFO basemod.BaseMod> postCreateStartingRelics adding [ Ring of the Snake ]
16:01:20.208 INFO basemod.BaseMod> postCreateStartingRelics for: DEFECT
16:01:20.209 INFO basemod.BaseMod> postCreateStartingRelics adding [ Cracked Core ]
16:01:20.287 INFO basemod.BaseMod> begin editing characters
16:01:20.295 INFO core.CardCrawlGame> [GC] BEFORE: 111457064
16:01:20.365 INFO core.CardCrawlGame> [GC] AFTER: 20204608
16:01:20.370 INFO basemod.BaseMod> publishPostInitialize
16:01:20.435 INFO basemod.BaseMod> registerModBadge : BaseMod
16:01:20.436 INFO basemod.ModBadge> initialized mod badge for: BaseMod
16:01:20.436 INFO basemod.ModBadge> setup hooks for BaseMod mod badge
16:01:20.438 INFO basemod.BaseMod> initializeUnderscoreCardIDs
16:01:20.439 INFO basemod.BaseMod> initializeUnderscorePotionIDs
16:01:20.439 INFO basemod.BaseMod> initializeUnderscoreEventIDs
16:01:20.439 INFO basemod.BaseMod> initializeUnderscoreRelicIDs
16:01:20.440 INFO basemod.BaseMod> initializeEncounters
16:01:20.530 INFO basemod.BaseMod> registerModBadge : BetterRewards
16:01:20.531 INFO basemod.ModBadge> initialized mod badge for: BetterRewards
16:01:20.531 INFO basemod.ModBadge> setup hooks for BetterRewards mod badge
Changing accessibility of AbstractRoom fields start
Changing accessibility of AbstractRoom fields end
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: rOutline
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: rOutline
	at coloredmap.ColoredMap.createIcon(ColoredMap.java:139)
	at coloredmap.ColoredMap.receivePostInitialize(ColoredMap.java:65)
	at basemod.BaseMod.publishPostInitialize(BaseMod.java:1980)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostInitializeHook.Postfix(PostInitializeHook.java:9)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:300)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by NicoTine34** [comment]
seems like its from ColoredMap mod :/

**Comment by kiooeht** [comment]
It's because you're using old versions of ModTheSpire and BaseMod.
ColoredMap is using newer parts of BaseMod, thus causing your issue.
All of the latest updates to ModTheSpire and BaseMod are available on the [Steam Workshop](https://steamcommunity.com/app/646570/workshop/).
