### ISSUE TITLE
Campfire Crash

### ISSUE THREAD

**Issue by AvangionQ** [kiooeht/ModTheSpire#144]
I'm pretty sure it's the relic that gives a free rest that's causing the crash. Only problem, I can't continue to check what the name of the relic is ... if I see it again, I'll make sure to edit this post.

-

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.ui.campfire.RestOption: method <init>()V not found
	at infinitespire.ui.FlaskOption.<init>(FlaskOption.java:20)
	at infinitespire.patches.CampfirePatch$InitializeButtons.Postfix(CampfirePatch.java:27)
	at com.megacrit.cardcrawl.rooms.CampfireUI.initializeButtons(CampfireUI.java:152)
	at com.megacrit.cardcrawl.rooms.CampfireUI.<init>(CampfireUI.java:59)
	at com.megacrit.cardcrawl.rooms.RestRoom.onPlayerEntry(RestRoom.java:35)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2322)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:582)
	at com.megacrit.cardcrawl.dungeons.TheBeyond.<init>(TheBeyond.java:76)
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1403)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:862)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by kiooeht** [comment]
It looks like you're using an old version of Infinite Spire and need to switch to using the Steam Workshop.
https://steamcommunity.com/sharedfiles/filedetails/?id=1610128058

**Comment by AvangionQ** [comment]
Please add that new version as a JAR file to ... https://github.com/GraysonnG/InfiniteSpire/releases
