### ISSUE TITLE
End of turn crash

### ISSUE THREAD

**Issue by AvangionQ** [kiooeht/ModTheSpire#151]
This is a new one, I'm not sure what's causing it, but it happens when I hit End Turn.

Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
15:45:53.129 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.screens.select.HandCardSelectScreen.prep(HandCardSelectScreen.java:783) ~[?:?]
	at com.megacrit.cardcrawl.screens.select.HandCardSelectScreen.open(HandCardSelectScreen.java:565) ~[?:?]
	at com.megacrit.cardcrawl.actions.unique.RetainCardsAction.update(RetainCardsAction.java:25) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
Reproducible crash, my guess is that two relics conflict.

16:02:55.147 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.screens.select.HandCardSelectScreen.prep(HandCardSelectScreen.java:783) ~[?:?]
	at com.megacrit.cardcrawl.screens.select.HandCardSelectScreen.open(HandCardSelectScreen.java:565) ~[?:?]
	at com.megacrit.cardcrawl.actions.unique.RetainCardsAction.update(RetainCardsAction.java:25) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:155) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by kiooeht** [comment]
This isn't a modded bug. This is a bug in Slay the Spire. Opening any hand card selection (in this case retaining cards) while the hand is empty while using a controller crashes the game.
