### ISSUE TITLE
Crash entering event: goblin matching game

### ISSUE THREAD

**Issue by AvangionQ** [kiooeht/ModTheSpire#157]
07:06:26.973 INFO dungeons.AbstractDungeon> Game Seed: -779080742953413481
07:06:26.974 INFO infinitespire.InfiniteSpire> adding initial quests
07:06:26.974 INFO dungeons.AbstractDungeon> Map generation time: 20ms
07:06:26.974 INFO dungeons.AbstractDungeon> [INFO] Elite nodes identified: 12
07:06:26.974 INFO dungeons.AbstractDungeon> [INFO] Emerald Key  placed in: [3,11]
07:06:26.976 DEBUG replayTheSpire.ReplayTheSpireMod> Poral A : (2, 7)
07:06:26.977 DEBUG replayTheSpire.ReplayTheSpireMod> Poral B : (6, 7)
07:06:26.979 INFO dungeons.AbstractDungeon> Loading into: 0,3
com.megacrit.cardcrawl.rooms.EventRoom
com.megacrit.cardcrawl.rooms.EmptyRoom
07:06:26.982 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
07:06:26.984 INFO helpers.EventHelper> Rolling for room type... EVENT_RNG_COUNTER: 2
07:06:26.984 INFO helpers.EventHelper> ROLL: 0.7083431
07:06:26.985 INFO helpers.EventHelper> ELIT: 0.2
07:06:26.986 INFO helpers.EventHelper> MNST: 0.3
07:06:26.987 INFO helpers.EventHelper> SHOP: 0.089999996
07:06:26.988 INFO helpers.EventHelper> TRSR: 0.099999994
07:06:26.989 INFO dungeons.AbstractDungeon> GENERATING ROOM: EVENT
07:06:26.990 INFO dungeons.AbstractDungeon> Removed event: Match and Keep! from pool.
07:06:27.006 INFO unlock.UnlockTracker> Already seen: strawberrySpire:Teyered
Exception: java.lang.NullPointerException
07:06:27.010 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.initializeCards(GremlinMatchGame.java:81) ~[?:?]
	at com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.<init>(GremlinMatchGame.java:53) ~[?:?]
	at com.megacrit.cardcrawl.helpers.EventHelper.getEvent(EventHelper.java:309) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getShrine(AbstractDungeon.java:2476) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.generateEvent(AbstractDungeon.java:2400) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.onPlayerEntry(EventRoom.java:24) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2322) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:582) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:110) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1399) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:862) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by AvangionQ** [comment]
Looks like I got it again, this crashes my game, no reload possible ... have to abandon the run to remedy.

19:24:08.144 INFO dungeons.AbstractDungeon> Game Seed: -1882241365542900443
19:24:08.144 INFO infinitespire.InfiniteSpire> adding initial quests
19:24:08.146 INFO dungeons.AbstractDungeon> Map generation time: 32ms
19:24:08.150 DEBUG replayTheSpire.ReplayTheSpireMod> Poral A : (0, 5)
19:24:08.150 DEBUG replayTheSpire.ReplayTheSpireMod> Poral B : (7, 5)
19:24:08.150 INFO dungeons.AbstractDungeon> Loading into: 4,4
com.megacrit.cardcrawl.rooms.EventRoom
com.megacrit.cardcrawl.rooms.EmptyRoom
19:24:08.155 INFO dungeons.AbstractDungeon> UNSPECIFIED CASE: NONE
19:24:08.157 INFO helpers.EventHelper> Rolling for room type... EVENT_RNG_COUNTER: 12
19:24:08.157 INFO helpers.EventHelper> ROLL: 0.84886193
19:24:08.158 INFO helpers.EventHelper> ELIT: 0.1
19:24:08.160 INFO helpers.EventHelper> MNST: 0.2
19:24:08.161 INFO helpers.EventHelper> SHOP: 0.06
19:24:08.161 INFO helpers.EventHelper> TRSR: 0.06
19:24:08.161 INFO dungeons.AbstractDungeon> GENERATING ROOM: EVENT
19:24:08.163 INFO dungeons.AbstractDungeon> Removed event: Match and Keep! from pool.
19:24:08.175 INFO unlock.UnlockTracker> Already seen: strawberrySpire:AscendersBanana
Exception: java.lang.NullPointerException
19:24:08.179 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.initializeCards(GremlinMatchGame.java:81) ~[?:?]
	at com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.<init>(GremlinMatchGame.java:53) ~[?:?]
	at com.megacrit.cardcrawl.helpers.EventHelper.getEvent(EventHelper.java:309) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.getShrine(AbstractDungeon.java:2476) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.generateEvent(AbstractDungeon.java:2400) ~[?:?]
	at com.megacrit.cardcrawl.rooms.EventRoom.onPlayerEntry(EventRoom.java:24) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.nextRoomTransition(AbstractDungeon.java:2322) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.populatePathTaken(AbstractDungeon.java:582) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.Exordium.<init>(Exordium.java:110) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.getDungeon(CardCrawlGame.java:1399) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:862) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.
