### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by ajman444** [kiooeht/ModTheSpire#16]
When I attempt to launch ModTheSpire version 2.4.0, after selecting play with only basemod selected, I get and error in the log. Here is the log for reference.
`Finding core patches...
com.badlogic.gdx.backends.lwjgl.LwjglApplication superclasses: 2
com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen superclasses: 2
com.megacrit.cardcrawl.ui.panels.TopPanel superclasses: 2
com.megacrit.cardcrawl.credits.CreditsScreen superclasses: 2
Finding patches...
com.megacrit.cardcrawl.screens.SingleCardViewPopup superclasses: 2
com.megacrit.cardcrawl.rooms.AbstractRoom superclasses: 2
com.megacrit.cardcrawl.ui.panels.ExhaustPanel superclasses: 3
com.megacrit.cardcrawl.screens.stats.StatsScreen superclasses: 2
com.megacrit.cardcrawl.screens.DeathScreen superclasses: 2
com.megacrit.cardcrawl.screens.mainMenu.MenuButton superclasses: 2
com.megacrit.cardcrawl.ui.panels.EnergyPanel superclasses: 3
com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen superclasses: 2
com.megacrit.cardcrawl.screens.charSelect.CharacterSelectScreen superclasses: 2
com.megacrit.cardcrawl.cards.AbstractCard superclasses: 2
com.megacrit.cardcrawl.relics.AbstractRelic superclasses: 2
com.megacrit.cardcrawl.potions.AbstractPotion superclasses: 2
com.megacrit.cardcrawl.core.CardCrawlGame superclasses: 2
com.megacrit.cardcrawl.shop.ShopScreen superclasses: 2
com.megacrit.cardcrawl.ui.panels.PotionPopUp superclasses: 2
com.megacrit.cardcrawl.unlock.UnlockTracker superclasses: 2
com.megacrit.cardcrawl.characters.AbstractPlayer superclasses: 3
com.megacrit.cardcrawl.core.EnergyManager superclasses: 2
com.megacrit.cardcrawl.localization.LocalizedStrings superclasses: 2
com.megacrit.cardcrawl.rewards.RewardItem superclasses: 2
com.megacrit.cardcrawl.ui.campfire.AbstractCampfireOption superclasses: 2
com.megacrit.cardcrawl.screens.options.SettingsScreen superclasses: 2
com.megacrit.cardcrawl.screens.stats.CharStat superclasses: 2
com.megacrit.cardcrawl.ui.buttons.CancelButton superclasses: 2
com.megacrit.cardcrawl.map.MapGenerator superclasses: 2
com.megacrit.cardcrawl.events.thecity.KnowingSkull superclasses: 4
com.megacrit.cardcrawl.helpers.PotionHelper superclasses: 2
com.megacrit.cardcrawl.vfx.CardTrailEffect superclasses: 3
com.megacrit.cardcrawl.ui.panels.DrawPilePanel superclasses: 3
com.megacrit.cardcrawl.helpers.RelicLibrary superclasses: 2
com.megacrit.cardcrawl.actions.GameActionManager superclasses: 2
com.megacrit.cardcrawl.ui.panels.DiscardPilePanel superclasses: 3
com.megacrit.cardcrawl.screens.mainMenu.CardLibraryScreen superclasses: 2
com.megacrit.cardcrawl.rooms.CampfireUI superclasses: 2
com.megacrit.cardcrawl.powers.IntangiblePower superclasses: 3
com.megacrit.cardcrawl.shop.StorePotion superclasses: 2
com.megacrit.cardcrawl.gashapon.NeowReward superclasses: 2
com.megacrit.cardcrawl.screens.charSelect.CharacterOption superclasses: 2
com.megacrit.cardcrawl.helpers.GameDictionary superclasses: 2
com.megacrit.cardcrawl.helpers.CardLibrary superclasses: 2
com.megacrit.cardcrawl.screens.options.OptionsPanel superclasses: 2
com.megacrit.cardcrawl.ui.buttons.EndTurnButton superclasses: 2
com.megacrit.cardcrawl.dungeons.AbstractDungeon superclasses: 2
com.megacrit.cardcrawl.actions.common.ApplyPowerAction superclasses: 3
com.megacrit.cardcrawl.actions.common.ObtainPotionAction superclasses: 3
com.megacrit.cardcrawl.cards.CardGroup superclasses: 2
com.megacrit.cardcrawl.ui.panels.TopPanel superclasses: 2
com.megacrit.cardcrawl.monsters.MonsterGroup superclasses: 2
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.
Setting isModded = true...Done.
Adding ModTheSpire to version...Done.
Initializing mods...
libgdx version 1.9.5
20:18:02.511 INFO basemod.BaseMod> initializeGson
20:18:02.569 INFO basemod.BaseMod> initializeTypeMaps

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:32)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:154)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:71)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/powers/AbsorbPower
	at basemod.BaseMod.initializePowerMap(BaseMod.java:568)
	at basemod.BaseMod.initialize(BaseMod.java:367)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.powers.AbsorbPower
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 10 more`

**Comment by ajman444** [comment]
Woops, this is totally not your problem. BaseMod was broken.
