### ISSUE TITLE
PatchingException: Illegal patch parameter

### ISSUE THREAD

**Issue by Shouxh** [kiooeht/ModTheSpire#169]
when I use any mod, the MTS will throw **PatchingException**, I tried to run it on windows & ubuntu, but all report the same exception.

but if i don't use any mod, it can run the game normally. the strange is I can play it normally yesterday, i can't comprehend. what's wrong with it?

**log:**
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-17-2019)
 - ModTheSpire (3.12.0)
Mod list:
 - basemod (5.15.1)
 - stslib (1.17.1)
 - decksortmod (3.0.0)
 - PrismaMod (1.2.4)
 - New YGO (0.0.1)
 - Remilia_Modoki (0.0.9)
 - superfastmode (1.0.6)
 - Konpaku_Youmu (0.0.9)

Begin patching...
Patching enums...Done.
Finding core patches...
Finding patches...
Patching Overrides...
Injecting patches...
```
Patch Class: [brainfubar.decksortmod.patches.CardFilterPatch$FlipFilteredCards]
 - Patching [com.megacrit.cardcrawl.screens.MasterDeckViewScreen.updatePositions()]
 - Adding Insert @ r20 (abs:246)...

com.evacipated.cardcrawl.modthespire.patcher.PatchingException: Illegal patch parameter: Cannot determine name
	at com.evacipated.cardcrawl.modthespire.patcher.ParameterPatchInfo$ParamTransformer.getParamName(ParameterPatchInfo.java:161)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo$InsertParamTransformer.getParamName(InsertPatchInfo.java:106)
	at com.evacipated.cardcrawl.modthespire.patcher.ParameterPatchInfo$ParamTransformer.makeSource(ParameterPatchInfo.java:197)
	at com.evacipated.cardcrawl.modthespire.patcher.ParameterPatchInfo.doPatch(ParameterPatchInfo.java:66)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:10)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:217)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:346)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:265)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kiooeht** [comment]
This is an issue with the DeckSortMod. It was using SpirePatch incorrectly but the error is only now being caught after the new ModTheSpire update.
Luckily, the deck sort feature was merged into the base game a while ago, so you can stop using DeckSortMod.
