### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by apynnonen** [kiooeht/ModTheSpire#18]
javassist.CannotCompileException: [source error] no such field: retVal
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:105)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:125)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:153)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:181)
	at java.lang.Thread.run(Unknown Source)
Caused by: compile error: no such field: retVal
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 6 more

**Comment by apynnonen** [comment]
As a note, I am trying to just install FruityMod atm. I have the newest version of Java, StS, and I downloaded the latest versions of everything. Not sure what's up. If you need additional things from me, let me know.

**Comment by daviscook477** [comment]
Does latest version of java mean version 9/10? Only version eight is supported currently

**Comment by apynnonen** [comment]
Sorry, I have java 8 i believe, an updated version of BaseMod was released an hour ago which when replaced, worked just fine. Thank you for your quick response.
