### ISSUE TITLE
I have java 8 but still ''NoSuchMethodException''

### ISSUE THREAD

**Issue by newbienoobplayer** [kiooeht/ModTheSpire#201]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
Yes/No.
yes i have read the guide 

**Crash Log**
```
ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (null)
 - ModTheSpire (3.6.3)
Mod list:
 - basemod (5.5.0)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.DeathScreen.ForceUnlock:
No method named [calculateUnlockProgress] found on
class [com.megacrit.cardcrawl.screens.DeathScreen]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:185)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional context**
![image](https://github.com/kiooeht/ModTheSpire/assets/138718840/f9ee3405-444a-44c1-9618-f3330d220cca)
I have downloaded 3 java 8s but there is still ''NoSuchMethodException''
![image](https://github.com/kiooeht/ModTheSpire/assets/138718840/afb8e7db-9b01-474f-955d-4632198097c9)

**Comment by Toerktumlare** [comment]
it says `basemod.patches.com.megacrit` megacrit are the devs of STS meaning it sort of looks like you are missing a Method that should be in the slay the spire game. Make sure you have updated the game and that the jar is placed correctly

**Comment by newbienoobplayer** [comment]
I will try, thank you

**Comment by banchl** [comment]
I had the same problem as you. The latest release version of ModTheSpire is only 3.6.3.
You need to package the latest code version 3.30.3 locally.
Or you can try the files I packed 
https://github.com/banchl/ModTheSpire/releases/tag/v3.30.3

**Comment by newbienoobplayer** [comment]
> I had the same problem as you. The latest release version of ModTheSpire is only 3.6.3. You need to package the latest code version 3.30.3 locally. Or you can try the files I packed https://github.com/banchl/ModTheSpire/releases/tag/v3.30.3

thanks
