### ISSUE TITLE
SpirePatch: Replace. Unknown return object.

### ISSUE THREAD

**Issue by Lyraedan** [kiooeht/ModTheSpire#203]
Writing a Library to extend orbs.
For this library to work with every orb I need to replace the "use(player, monster)" function inside the Defects orb cards.

This is what I have thus far.
@SpirePatch(clz = Zap.class, method = "use", paramtypez = { AbstractPlayer.class, AbstractMonster.class, })
public class DefectPatch {
	public static Object Replace(Zap __instance, AbstractPlayer p, AbstractMonster m) {
		boolean isDefect = AbstractDungeon.player instanceof com.megacrit.cardcrawl.characters.Defect;
		for (int i = 0; i < __instance.magicNumber; i++) {
			AbstractDungeon.actionManager.addToBottom(new SpellweaverChannelAction(new DefectZapOrb(), !isDefect));
		}
		return __instance;
	}
}

I look at the docs here https://github.com/kiooeht/ModTheSpire/wiki/SpirePatch#replace
However in the the replace function only contains "..." and does not say what should be returned.
Running my code as it crashes with the error

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ClassFormatError: StackMapTable format error: bad type array size in method com.megacrit.cardcrawl.cards.blue.Zap.use(Lcom/megacrit/cardcrawl/characters/AbstractPlayer;Lcom/megacrit/cardcrawl/monsters/AbstractMonster;)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.ClassFormatError: StackMapTable format error: bad type array size in method com.megacrit.cardcrawl.cards.blue.Zap.use(Lcom/megacrit/cardcrawl/characters/AbstractPlayer;Lcom/megacrit/cardcrawl/monsters/AbstractMonster;)V
	at com.megacrit.cardcrawl.helpers.CardLibrary.addBlueCards(CardLibrary.java:695)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java:417)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:282)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

What exactly am I suppose to be returning if its a void function? Returning null doesn't work. Should this not be mentioned on the docs? Am I missing something?

**Comment by Lyraedan** [comment]
My solution to this was to use a prefix patch of the type SpireReturn Void and return SpireReturn.Return() to prevent execution of the code i'm trying to replace.
