### ISSUE TITLE
game not initializing, java error

### ISSUE THREAD

**Issue by ofbruno2** [kiooeht/ModTheSpire#23]
hey guys, I'm getting this error message when opening modthespire
already tried reinstalling slay the spire and java 8 but still the same message, any help?
running on windows 10

![spr](https://user-images.githubusercontent.com/37948855/38159980-12292c4e-348b-11e8-9c32-9206d7788c45.jpg)

"
Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.
Setting isModded = true...
Exception in thread "Thread-3" java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: Provider org.apache.logging.log4j.core.impl.Log4jProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.logging.log4j.util.ProviderUtil.loadProviders(ProviderUtil.java:101)
	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:142)
	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:126)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:89)
	at com.megacrit.cardcrawl.core.Settings.<clinit>(Settings.java:16)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:167)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:181)
	at java.lang.Thread.run(Thread.java:748)
"

**Comment by kiooeht** [comment]
What mods were you trying to use?

**Comment by daviscook477** [comment]
The failure seems to be happening because on line 176 ModTheSpire is trying to set `isModded` in the game's `Settings` object which when forced to be classloaded is trying to setup its static fields, one of which is the logger that is causing the exception.

**Comment by ofbruno2** [comment]
I tried loading BaseMod and Necromod respectively, guess I followed all the instructions correctly

**Comment by ofbruno2** [comment]
Just figured it out... All I had to do was set Java as the default program for opening .jar files instead of using 'Open with', somehow it wont work that way

Everything working now :)
