### ISSUE TITLE
Can Mac use the mod?

### ISSUE THREAD

**Issue by icicle4** [kiooeht/ModTheSpire#30]
Thought You don't mention the mac in the doc.I use it as Linux.
 I got it but then get a wrong as
 "ERROR: Failed to find Steam installation.
        Exception in thread "main" java.lang.NullPointerException
	at com.evacipated.cardcrawl.modthespire.SteamSearch.containsAcfFile(SteamSearch.java:94)
	at com.evacipated.cardcrawl.modthespire.SteamSearch.prepare(SteamSearch.java:39)
	at com.evacipated.cardcrawl.modthespire.SteamSearch.findDesktopJar(SteamSearch.java:19)
	at com.evacipated.cardcrawl.modthespire.Loader.main(Loader.java:83)".

If Mac are in plan, please tell me, thanks.

**Comment by icicle4** [comment]
I got it. it shoud be put in the Source fold.
