### ISSUE TITLE
javassist.CannotCompileException: [source error] no such field: cards

### ISSUE THREAD

**Issue by inuyasha1001** [kiooeht/ModTheSpire#32]
This error pops up when I run ModTheSpire. Any solution to this ?

**Comment by StaticAshes** [comment]
Hello I have the same problem, this is the full log for me.

Debug mode!
Java version: 1.8.0_144
Slay the Spire version: 04-12-2018
ModTheSpire version: 2.6.0
Mod list: Base Mod, ReplayTheSpireMod, 
Finding core patches...
Finding patches...
Injecting patches...
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.setMainMenuButtons()]
    Adding Insert @ r4 (abs:147)...

{
int[] __index = new int[]{index};
com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem.Insert($0, $$, __index);
index = __index[0];
}
Patch [com.evacipated.cardcrawl.modthespire.patches.modsscreen.SaveBaseModBadges]
  Patching [basemod.BaseMod.registerModBadge(com.badlogic.gdx.graphics.Texture,java.lang.String,java.lang.String,java.lang.String,basemod.ModPanel)]
    Adding Insert @ r8 (abs:272)...

{
com.evacipated.cardcrawl.modthespire.patches.modsscreen.SaveBaseModBadges.Insert($$, badge);
}
Patch [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
  Patching [com.megacrit.cardcrawl.credits.CreditsScreen()]
    Adding Insert @ r5 (abs:55)...

{
float[] __tmpY = new float[]{tmpY};
com.evacipated.cardcrawl.modthespire.patches.CreditsModList.Insert($0, $$, __tmpY);
tmpY = __tmpY[0];
}
Patch [com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit]
  Patching [com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()]
    Adding Insert @ 248...

{
com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.StartActHook]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.update()]
    Adding Insert @ 778...

{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.StartActHook.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterDeckHookSwitch]
  Patching [com.megacrit.cardcrawl.characters.AbstractPlayer.initializeStarterDeck()]
    Adding Insert @ 246...

{
java.util.ArrayList[] __cards = new java.util.ArrayList[]{cards};
basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterDeckHookSwitch.Insert($0, $$, __cards);
cards = __cards[0];
}
javassist.CannotCompileException: [source error] no such field: cards
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:135)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:149)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:145)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:189)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: compile error: no such field: cards
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.TypeChecker.atArrayInit(TypeChecker.java:186)
	at javassist.compiler.ast.ArrayInit.accept(ArrayInit.java:29)
	at javassist.compiler.TypeChecker.atNewArrayExpr(TypeChecker.java:162)
	at javassist.compiler.TypeChecker.atNewExpr(TypeChecker.java:144)
	at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:743)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by kiooeht** [comment]
You're using an extremely old version of BaseMod. Get the latest release from https://github.com/daviscook477/BaseMod/releases

**Comment by StaticAshes** [comment]
thank you! it worked!
