### ISSUE TITLE
This error showed up today when I tried to load up the mod

### ISSUE THREAD

**Issue by inuyasha1001** [kiooeht/ModTheSpire#36]
Java version: 1.8.0_144
Slay the Spire version: 04-26-2018
ModTheSpire version: 2.6.0
Mod list: basemod (2.6.0), NecroMod, 
Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.
Setting isModded = true...Done.
Adding ModTheSpire to version...Done.
Initializing mods...
libgdx version 1.9.5
15:23:04.239 INFO basemod.BaseMod> initializeGson
15:23:04.246 INFO basemod.BaseMod> initializeTypeMaps

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:34)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:217)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/megacrit/cardcrawl/powers/DarknessPower
	at basemod.BaseMod.initializePowerMap(BaseMod.java:700)
	at basemod.BaseMod.initialize(BaseMod.java:475)
	... 8 more
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.powers.DarknessPower
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	... 10 more

**Comment by inuyasha1001** [comment]
Thanks for the help!
