### ISSUE TITLE
Mod the Spire

### ISSUE THREAD

**Issue by XsPaReS** [kiooeht/ModTheSpire#38]
It keeps crashing everytime the game open and i dont understand why any help would be appreciated

**Comment by kiooeht** [comment]
Can you provide any more information or a log?

**Comment by oligarky** [comment]
I'm having an issue with launching when I have just the base mod installed
log:
Finding core patches...
Finding patches...
ERROR: No method [getPotion] found on class [com.megacrit.cardcrawl.gashapon.NeowReward]
ERROR: No method [obtainPotion] found on class [com.megacrit.cardcrawl.helpers.PotionHelper]
Injecting patches...
javassist.CannotCompileException: [source error] no such field: i
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:105)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:125)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:153)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:181)
	at java.lang.Thread.run(Unknown Source)
Caused by: compile error: no such field: i
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 6 more

**Comment by kiooeht** [comment]
@oligarky You need to update to the newest version of BaseMod. Last week's game update broke it, but BaseMod has since been updated to work.

**Comment by Downanddirty4568** [comment]
i have continuously updated the base mod and all of my other mods consistently and i continuously check if there is a new mod the spire update from you but there never is , mod the spire was literally working perfectly fine last night, just last night i was playing it all night without any problems , i wake up this morning boom all the sudden its not working with the same exact files i had last night, i didnt change anything.....
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.core.CardCrawlGame.update: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PreUpdateHook$Locator.Locate(UpdateHooks.java:40)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:265)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Unknown Source)
