### ISSUE TITLE
Mod The spire messing up again

### ISSUE THREAD

**Issue by Downanddirty4568** [kiooeht/ModTheSpire#44]
i mentioned this on another post as a reply to someone who was having a similar problem, but i wanted to make my own post about this so maybe it will get attention faster because i really want to play mod the spire today, ModTheSpire was working JUST fine last night literally right before i went to bed last night at like 12am i was playing it without any problems
yet all the sudden im having issues with it this morning, when i have yet to change any files, although after it didnt work the first time i went to update my base mod and i updated the constructmod, but it still doesnt work. this is what it gives me when i try to start it up:

Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.core.CardCrawlGame.update: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PreUpdateHook$Locator.Locate(UpdateHooks.java:40)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:265)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:170)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:185)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$1(ModSelectWindow.java:189)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
I can't be certain without a full log, but I'm guessing you're running the beta branch of the game.

ModTheSpire and BaseMod do not support the beta branch because it changes so often. The beta branch updated last night and probably introduced a change that broke BaseMod.

**Comment by Downanddirty4568** [comment]
Cool thanks it works again it was the beta mode thing
