### ISSUE TITLE
ModTheSpire Doesn't Work

### ISSUE THREAD

**Issue by GChroma** [kiooeht/ModTheSpire#47]
Whenever I start it, it shows this.

Running with debug mode turned ON...

Version Info:
 - Java version (1.8.0_171)
 - Slay the Spire (06-07-2018)
 - ModTheSpire (2.7.0)
Mod list:
 - basemod (2.14.0)
 - fruitymod-sts (0.6.8)
 - JuggerMod

Begin patching...
Finding core patches...
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: com.megacrit.cardcrawl.core.CardCrawlGame.update: Location matching given description could not be found for patch
	at com.evacipated.cardcrawl.modthespire.lib.LineFinder.findInOrder(LineFinder.java:30)
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.UpdateHooks$PreUpdateHook$Locator.Locate(UpdateHooks.java:34)
	at com.evacipated.cardcrawl.modthespire.patcher.LocatorInfo.findLines(LocatorInfo.java:18)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:270)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
You need to update your game. You're using an old version of the game (06-07-2018). The current version is (06-21-2018).

**Comment by GChroma** [comment]
thank you
