### ISSUE TITLE
Exception in thread "Thread-2" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by andel27** [kiooeht/ModTheSpire#56]
I use a mac and have downloaded the files accordingly. Starting through ModTheSpire.jar works fine and the game loads with not mods selected, but when I try to start with any mods selected this error comes up no matter which mod I choose. Anyone have the solution?

Exception in thread "Thread-2" java.lang.NoSuchMethodError: sun.reflect.ReflectionFactory.newConstructorAccessor(Ljava/lang/reflect/Constructor;)Lsun/reflect/ConstructorAccessor;
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.findConstructorAccessor(EnumBusterReflect.java:211)
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.make(EnumBusterReflect.java:70)
	at com.evacipated.cardcrawl.modthespire.EnumBusterReflect.make(EnumBusterReflect.java:49)
	at com.evacipated.cardcrawl.modthespire.Patcher.patchEnums(Patcher.java:125)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:237)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
I believe you're launching ModTheSpire.jar with Java 9. ModTheSpire does not support Java 9 and needs to be run with Java 8. Slay the Spire comes with Java 8 and ModTheSpire comes with a small script (MTS.sh) that runs ModTheSpire using the Java that Slay the Spire ships with.
