### ISSUE TITLE
Issue after todays update

### ISSUE THREAD

**Issue by slayingthespire** [kiooeht/ModTheSpire#58]
I updated everything as if i were freshly installing it after todays patch, and now get an error code that goes as follows:

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (2.7.0)
Mod list:

Starting game...
Exception in thread "Thread-4" java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: Provider org.apache.logging.log4j.core.impl.Log4jProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.logging.log4j.util.ProviderUtil.loadProviders(ProviderUtil.java:101)
	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:142)
	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:126)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:89)
	at com.megacrit.cardcrawl.desktop.DesktopLauncher.<clinit>(DesktopLauncher.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:300)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Thread.java:748)

I'm unable to play the vanilla version of the game, i'm not sure what i screwed up along the way. Any advice would be much appreciated

**Comment by kiooeht** [comment]
Step 1: Update ModTheSpire. 2.8.0 is out and while I don't think that will fix your issue, you might get lucky.
Step 2: Can you launch Slay the Spire normally? As in, outside of ModTheSpire, just with Steam.
Step 3: Verify your game files. Right click Slay the Spire in Steam, Properties > Local Files > Verify Integrity of Game Files.

**Comment by slayingthespire** [comment]
I cant start it normally through steam, it sends it right to the landing page of the mod, even after I verified integrity of game files

**Comment by kiooeht** [comment]
That shouldn't be possible. If you're launching the game through Steam, you shouldn't encounter ModTheSpire at all. Launching through Steam should take you straight to the normal game.

I'd suggest you uninstall and reinstall the game, make sure you can run it normally, then install ModTheSpire according to these instructions: https://github.com/kiooeht/ModTheSpire/wiki

**Comment by NoisyExo** [comment]
slayingthespire I had the same problem as u but I found a solution and it is to update ur Java to Java 8
