### ISSUE TITLE
No mods will load. TMP

### ISSUE THREAD

**Issue by Rhys-Prime** [kiooeht/ModTheSpire#62]
So I've verified my cache, am running the newest version of both the base mod and the mod the spire, but this error is occuring and it won't launch. 

javassist.CannotCompileException: [source error] no such field: tmp
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:132)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:146)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:146)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:233)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)
Caused by: compile error: no such field: tmp
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by kiooeht** [comment]
Can you provide the top of the log? It contains information about what mods you're using and what versions of MTS, StS, mods, etc. you're using

**Comment by Rhys-Prime** [comment]
Running with debug mode turned ON...

Version Info:
 - Java version (1.8.0_171)
 - Slay the Spire (07-13-2018) BETA
 - ModTheSpire (2.8.0)
Mod list:
 - witchmod (0.9.1)
 - basemod (2.16.0)

Begin patching...
Finding core patches...
Finding patches...
Injecting patches...

Patch Class: [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
 - Patching [com.megacrit.cardcrawl.credits.CreditsScreen()]
 - Adding Insert @ r5 (abs:57)...


Patch Class: [com.evacipated.cardcrawl.modthespire.patches.modsscreen.MainMenuItem]
 - Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.setMainMenuButtons()]
 - Adding Insert @ r4 (abs:143)...


Patch Class: [com.evacipated.cardcrawl.modthespire.patches.modsscreen.SaveBaseModBadges]
 - Patching [basemod.BaseMod.registerModBadge(com.badlogic.gdx.graphics.Texture,java.lang.String,java.lang.String,java.lang.String,basemod.ModPanel)]
 - Adding Insert @ r8 (abs:764)...


Patch Class: [com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit]
 - Patching [com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop()]
 - Adding Insert @ 248...


Patch Class: [witchmod.patches.BackToBasicsPatch]
 - Patching [com.megacrit.cardcrawl.events.thecity.BackToBasics.buttonEffect(int)]
 - Adding Insert @ r30 (abs:89)...


Patch Class: [witchmod.patches.VampiresPatch]
 - Patching [com.megacrit.cardcrawl.events.thecity.Vampires.replaceAttacks()]
 - Adding Insert @ r8 (abs:137)...


Patch Class: [witchmod.patches.GremlinMatchPatch]
 - Patching [com.megacrit.cardcrawl.events.shrines.GremlinMatchGame.initializeCards()]
 - Adding Insert @ r32 (abs:94)...


Patch Class: [witchmod.patches.PandorasBoxPatch]
 - Patching [com.megacrit.cardcrawl.relics.PandorasBox.onEquip()]
 - Adding Insert @ r12 (abs:47)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.relics.PandorasBox.OnEquip]
 - Patching [com.megacrit.cardcrawl.relics.PandorasBox.onEquip()]
 - Adding Insert @ r12 (abs:47)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.events.Vampires.ReplaceAttacks]
 - Patching [com.megacrit.cardcrawl.events.thecity.Vampires.replaceAttacks()]
 - Adding Insert @ r8 (abs:137)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHooks$RenderHook]
 - Patching [com.megacrit.cardcrawl.core.CardCrawlGame.render()]
 - Adding Insert @ 445...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.AddSwitch]
 - Patching [com.megacrit.cardcrawl.helpers.CardLibrary.add(com.megacrit.cardcrawl.cards.AbstractCard)]
 - Adding Insert @ r37 (abs:755)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.EverythingFix$DidChangeTab]
 - Patching [com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen.didChangeTab(com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar,com.megacrit.cardcrawl.screens.mainMenu.ColorTabBar$CurrentTab)]
 - Adding Insert @ r1 (abs:541)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHooks$PostRenderHook]
 - Patching [com.megacrit.cardcrawl.core.CardCrawlGame.render()]
 - Adding Insert @ 483...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.ui.panels.PotionPopUp.PostPotionUseHookTargetMode]
 - Patching [com.megacrit.cardcrawl.ui.panels.PotionPopUp.updateTargetMode()]
 - Adding Insert @ r24 (abs:228)...


Patch Class: [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.DamageHooks$CalculateCardDamageMulti]
 - Patching [com.megacrit.cardcrawl.cards.AbstractCard.calculateCardDamage(com.megacrit.cardcrawl.monsters.AbstractMonster)]
 - Adding Insert @ r77 (abs:2965)...

javassist.CannotCompileException: [source error] no such field: tmp
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:132)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:146)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:146)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:233)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)
Caused by: compile error: no such field: tmp
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by kiooeht** [comment]
You're running on the beta branch of the game. ModTheSpire and BaseMod do not support the beta branch. You need to switch to the main branch if you want to use mods.

Also, you should reorder your mods (drag and drop) so that BaseMod is first. Otherwise you'll encounter an error because the Witch needs to be loaded after BaseMod.

**Comment by Rhys-Prime** [comment]
https://www.twitch.tv/jrm1ah is currently streaming with it running on beta, though he's not using any mods currently he was in the last run... Hmmm

**Comment by Rhys-Prime** [comment]
I'll definitely try on Release version

**Comment by Rhys-Prime** [comment]
Otay, moving to release worked.
