### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Motejlyk** [kiooeht/ModTheSpire#66]
**Before submitting, have you read the [Troubleshooting guide]?
Yes.

**Crash Log**
```
Version Info:
 - Java version (1.8.0_171)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (2.8.0)
Mod list:
 - MadScienceMod (0.1.8)
 - basemod (2.16.0)

Begin patching...
Finding core patches...
Finding patches...
Injecting patches...Done.
Compiling patched classes...Done.
Patching enums...Done.

Setting isModded = true...Done.

Adding ModTheSpire to version...Done.

Initializing mods...
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:34)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:272)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at basemod.BaseMod.subscribeToPostInitialize(BaseMod.java:2716)
	at madsciencemod.MadScienceMod.<init>(MadScienceMod.java:68)
	at madsciencemod.MadScienceMod.initialize(MadScienceMod.java:79)
	... 8 more
```

**Additional context**
Every time I try to start the Mod the Spire 2.8.0 (first one I am trying) i click Play (even with Debug) it will send this error, is there any possible way to help me run it? :)

**Comment by Motejlyk** [comment]
Also I tried 4 different How to install mods to StS... neither of them worked

**Comment by KongMD-Steam** [comment]
@Motejlyk You have to drag Basemod higher than all other mods (it should be first in the list).

**Comment by Motejlyk** [comment]
Well....fok me...how come I did not see that one before? Thank You very much. (now I feel stupid for this issue)

**Comment by kiooeht** [comment]
You didn't see it because KongMD-Steam added it to the Troubleshooting guide an hour ago.
