### ISSUE TITLE
ERROR: No method [instantObtain] found on class [com.megacrit.cardcrawl.relics.AbstractRelic]

### ISSUE THREAD

**Issue by nmeddin** [kiooeht/ModTheSpire#67]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
Yes/No.

**Crash Log**
```
Running with debug mode turned ON...

Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (07-12-2018)
 - ModTheSpire (2.8.0)
Mod list:
 - basemod (2.5.0)
 - ReplayTheSpireMod (1.0.3)

Begin patching...
Finding core patches...
Finding patches...
ERROR: No method [instantObtain] found on class [com.megacrit.cardcrawl.relics.AbstractRelic]
javassist.NotFoundException: com.megacrit.cardcrawl.gashapon.NeowReward
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:229)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Thread.java:748)
```

This happens right after I run the MST script. basemod is always checked, replay is checked for one run, unchecked for another, same results.

**Comment by kiooeht** [comment]
You're using a really old version of BaseMod. You can get the newest version at https://github.com/daviscook477/BaseMod/releases/latest
