### ISSUE TITLE
Crash Upon Loading

### ISSUE THREAD

**Issue by vizthex123** [kiooeht/ModTheSpire#76]
Whenever I load up Mod the Spire, the game crashes. I don't know what's wrong with it, all my mods are up to date and so is BaseMod and Mod the Spire.

Crashlog here: https://pastebin.com/9rc8aQgF

**Comment by kiooeht** [comment]
I think you posted the wrong log.

That log looks to be for a non-modded 40 minute run, ending with death by the Awakened One.

**Comment by Conman5534** [comment]
Yeah, I can't load up the game either.

Crashlog here: [https://pastebin.com/Tv7svyFy](https://pastebin.com/Tv7svyFy)

**Comment by franzlucas03** [comment]
javassist.NotFoundException: com.megacrit.cardcrawl.ui.panels.RenamePanel
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:239)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

i figure out that using SuperFastMode make the game like this
Problem with SuperFastMode <<

**Comment by kiooeht** [comment]
@franzlucas03 See the issue you opened of the same problem (https://github.com/kiooeht/ModTheSpire/issues/77).
