### ISSUE TITLE
The SuperFastMode is not working

### ISSUE THREAD

**Issue by franzlucas03** [kiooeht/ModTheSpire#77]
when im using the mod "SuperFastMode" this problem appears:

javassist.NotFoundException: com.megacrit.cardcrawl.ui.panels.RenamePanel
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:239)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
Update SuperFastMode (https://github.com/Skrelpoid/SuperFastMode/releases/tag/v0.9.1).
SuperFastMode was broken by the last update to the game and only just updated to fix the problem.
