### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by GChroma** [kiooeht/ModTheSpire#79]
When I try to load Mod The Spire this shows up

Version Info:
 - Java version (1.8.0_181)
 - Slay the Spire (06-21-2018)
 - ModTheSpire (2.9.1)
Mod list:
 - basemod (2.19.0)
 - The Valiant

Begin patching...
Finding core patches...
Finding patches...
javassist.NotFoundException: com.megacrit.cardcrawl.screens.compendium.CardLibraryScreen
	at javassist.ClassPool.get(ClassPool.java:445)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:206)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:174)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:239)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:199)
	at java.lang.Thread.run(Unknown Source)

**Comment by kiooeht** [comment]
You're version of Slay the Spire is two months out of date.
