### ISSUE TITLE
NullPointerException Error

### ISSUE THREAD

**Issue by DragonHunter003** [kiooeht/ModTheSpire#8]
When attempting to load ModTheSpire through SlayTheSpire.exe after renaming the .jar files accordingly I keep getting the following error upon attempting to load the game with the BaseMod
`java.lang.NullPointerException: in is null
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:101)
	at java.util.zip.ZipInputStream.<init>(ZipInputStream.java:80)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:76)
	at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.<init>(MTSClassLoader.java:29)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:60)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$0(ModSelectWindow.java:83)
	at java.lang.Thread.run(Thread.java:748)`
This doesn't happen when running ModTheSpire.jar (Now named desktop-1.0.jar) directly

**Comment by kiooeht** [comment]
As it says [here](https://github.com/kiooeht/ModTheSpire/releases/tag/v2.1.0), running the game through `SlayTheSpire.exe` does not work currently.

I've now fixed this particular issue you encountered (4719becec267582e3492c2c30ceb6e29ad9e13fc and 44a790b98ef0648915ebfd0fe148a06e1ebbaf31), but the game still crashes when run through SlayTheSpire.exe (#9).
