### ISSUE TITLE
The game doesn't start 

### ISSUE THREAD

**Issue by DanMan2231** [kiooeht/ModTheSpire#86]
Hey so when I try to open the game trough the MTS it just does want to start it is what shows up and it does not do anything after. 

ModVersion Info:
 - Java version (1.8.0_144)
 - Slay the Spire (08-16-2018)
 - ModTheSpire (3.1.0)
Mod list:
 - basemod (3.1.1)

Begin patching...
Finding core patches...
Finding patches...
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy2.clz(Unknown Source)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:208)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:176)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:192)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.megacrit.cardcrawl.events.city.Vampires
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.findClass(MTSClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.evacipated.cardcrawl.modthespire.MTSClassLoader.loadClass(MTSClassLoader.java:65)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javassist.bytecode.annotation.MemberValue.loadClass(MemberValue.java:56)
	at javassist.bytecode.annotation.ClassMemberValue.getValue(ClassMemberValue.java:89)
	at javassist.bytecode.annotation.AnnotationImpl.invoke(AnnotationImpl.java:151)
	... 6 more

**Comment by kiooeht** [comment]
> Slay the Spire (08-16-2018)

You're using a 2 week old version of the game. Most recent version is 08-30-2018.
