### ISSUE TITLE
InvocationTargetException despite mods being in the right order

### ISSUE THREAD

**Issue by Ayotte** [kiooeht/ModTheSpire#89]
I have BaseMod at the top of my mod list, but I still get the exception that the wiki mentions relates to BaseMod not being at the top.

![2018-09-06 18_31_23-modthespire 3 1 0](https://user-images.githubusercontent.com/11084432/45190340-2201f600-b203-11e8-9dc3-006767a29ad8.jpg)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.evacipated.cardcrawl.modthespire.Patcher.initializeMods(Patcher.java:31)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:235)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at basemod.BaseMod.initializeEncounters(BaseMod.java:614)
	at basemod.BaseMod.initialize(BaseMod.java:344)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.megacrit.cardcrawl.helpers.MonsterHelper.<clinit>(MonsterHelper.java:89)
	... 16 more

**Comment by kiooeht** [comment]
The new game update broke BaseMod. You'll have to wait until BaseMod updates.

https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting#is-it-thursday-or-friday-or-sometimes-saturday

**Comment by kiooeht** [comment]
New version of BaseMod is out now: https://github.com/daviscook477/BaseMod/releases/tag/v3.2.1
