### ISSUE TITLE
game crashing on startup

### ISSUE THREAD

**Issue by tyler13542** [kiooeht/ModTheSpire#93]
**Before submitting, have you read the [Troubleshooting guide](https://github.com/kiooeht/ModTheSpire/wiki/Troubleshooting)?**
Yes/No.

**Crash Log**
```
Paste the ENTIRE log here. Including the very top of the log and the full error.
```
[troubleshoot.log](https://github.com/kiooeht/ModTheSpire/files/2464522/troubleshoot.log)

**Additional context**
i open it it opens closes that's it

**Comment by tyler13542** [comment]
in case that's the wrong crash log this is the only error I could find


Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: BRONZE
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchFieldError: BRONZE
	at replayTheSpire.ReplayTheSpireMod.initializeDecipleMod(ReplayTheSpireMod.java:1236)
	at replayTheSpire.ReplayTheSpireMod.initializeCrossoverRelics(ReplayTheSpireMod.java:1129)
	at replayTheSpire.ReplayTheSpireMod.receiveEditRelics(ReplayTheSpireMod.java:970)
	at basemod.BaseMod.publishEditRelics(BaseMod.java:2395)
	at basemod.patches.com.megacrit.cardcrawl.helpers.RelicLibrary.EditRelicsPatch.Prefix(EditRelicsPatch.java:12)
	at com.megacrit.cardcrawl.helpers.RelicLibrary.initialize(RelicLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:288)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)12:15:16.879 INFO helpers.File> Successfully saved file=C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\preferences\STSUnlocks

**Comment by kiooeht** [comment]
This looks like a problem with Replay the Spire. I've let the author know, they should fix it sometime soon.
