### ISSUE TITLE
doesent open

### ISSUE THREAD

**Issue by tyler13542** [kiooeht/ModTheSpire#95]
Finding patches...
com.evacipated.cardcrawl.modthespire.patcher.MissingParamTypesException: Patch basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.BlueCardsPatch
Patching com.megacrit.cardcrawl.helpers.CardLibrary.addBlueCards:
Has overloads and no paramtypes defined
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:264)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hencook** [comment]
I have the same issue; persists even after all mods are disabled.

**Comment by kiooeht** [comment]
Yesterday's update to the game brought a lot of backend changes to the game that break BaseMod in a lot of ways. I've been working on fixing it, but there are a lot of changes to work through, it will take some time.
