### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jayzaza1** [kiooeht/ModTheSpire#96]
java.lang.NullPointerException
	at com.evacipated.cardcrawl.modthespire.Loader.findDependencyIndex(Loader.java:476)
	at com.evacipated.cardcrawl.modthespire.Loader.orderDependencies(Loader.java:493)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:169)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kiooeht** [comment]
This is a very unhelpful crash report, but I think it's an issue that v3.3.0 (the new release) fixes.
