### ISSUE TITLE
Error on loading the modthespire

### ISSUE THREAD

**Issue by AdreBucurel** [kiooeht/ModTheSpire#99]
Trying all day to run the modthespire but every time i get this error, i tryed diferent version of the slay the spire and nothing worked. I don't have the game on the steam, i downloaded from igg game.

Running with debug mode turned ON...

ModVersion Info:
 - Java version (1.8.0_171)
 - Slay the Spire (10-04-2018)
 - ModTheSpire (3.3.0)
Mod list:
 - basemod (4.0.1)
 - MadScienceMod (0.2.3)

Begin patching...
Finding core patches...
Finding patches...
java.lang.NoSuchMethodException: Patch basemod.patches.com.megacrit.cardcrawl.screens.charSelect.CharacterOption.CtorSwitch:
No method [<ctor>(java.lang.String, com.megacrit.cardcrawl.characters.AbstractPlayer, java.lang.String, java.lang.String)] found on
class [com.megacrit.cardcrawl.screens.charSelect.CharacterOption]
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:271)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:179)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:191)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Unknown Source)

**Comment by yhrcyt** [comment]
Update your slay the spire.

**Comment by yhrcyt** [comment]
Your slay the spire is not the latest version.

**Comment by AdreBucurel** [comment]
Thx, that work
